player-tag:
  name-tag: "&6&l%factions_faction% &r&e%player%"
  score-tag: "&e{division}&f | %player_health%&c❤ &7- &3%device_os%"

chat:
  format: "&l%envy_faction%&r &3[&l%luckperms_prefix%&r&3]&e%player% &3⋙&f %msg%"

scoreboard:
  update: 20
  titles:
    - "§3EnvyGames §c✕ §4Factions"
    - "§3 EnvyGame §c✕ §cFactions"
    - "§3  EnvyGam §c✕ §6Factions"
    - "§3   EnvyGa §c✕ §eFactions"
    - "§3    EnvyG §c✕ §2Factions"
    - "§3     Envy §c✕ §aFactions"
    - "§3      Env §c✕ §bFactions"
    - "§3       En §c✕ §3Factions"
    - "§3        E §c✕ §1Factions"
    - "§3s         §c✕ §9Factions"
    - "§3es        §c✕ §dFactions"
    - "§3mes       §c✕ §5Factions"
    - "§3ames      §c✕ §fFactions"
    - "§3Games     §c✕ §7Factions"
    - "§3yGames    §c✕ §8Factions"
    - "§3vyGames   §c✕ §0Factions"
    - "§3nvyGames  §c✕ §3Factions"
  lines:
    - "§c┍╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾"
    - "§c╿ §aName§c: §3%player%"
    - "§c╿ §aFaction§c: §3%factions_faction%"
    - "§c╿ §aLevel§c: §3{level}"
    - "§c╿ §aExp§c: §3{exp}/{expTLU}"
    - "§c╿ §aDivision§c: §3{division}"
    - "§c╿ §aDivisionRank§c: §3{divisionRank}"
    - "§c╿ §aProfession§c: §3unlock at lvl20"
    - "§c╿ §aBalance§c: §3%economy_money%"
    - "§c╿ §aPing§c: §3{ping}%"
    - "§c┕╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾"